### ISSUE TITLE
Error: Dynamic Symbol Retrieval Error: Win32 error 127

### ISSUE THREAD

**Issue by clansty** [sewerganger/win-win#3]
Error when calling `Win32ffi.winFns()` on Windows 7

Electron 18.2.0

```
Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (D:\ClassTools\node_modules\ffi-napi\lib\dynamic_library.js:113:11)
    at D:\ClassTools\node_modules\ffi-napi\lib\library.js:55:21
    at Array.forEach (<anonymous>)
    at Object.Library (D:\ClassTools\node_modules\ffi-napi\lib\library.js:52:28)
    at Win32ffi2.user32 (D:\ClassTools\dist\main\setAsWallpaper.js:2297:21)
    at Win32ffi2.winFns (D:\ClassTools\dist\main\setAsWallpaper.js:2304:37)
    at Module.<anonymous> (D:\ClassTools\dist\main\setAsWallpaper.js:2366:36)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
(node:2264) UnhandledPromiseRejectionWarning: Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (D:\ClassTools\node_modules\ffi-napi\lib\dynamic_library.js:113:11)
    at D:\ClassTools\node_modules\ffi-napi\lib\library.js:55:21
    at Array.forEach (<anonymous>)
    at Object.Library (D:\ClassTools\node_modules\ffi-napi\lib\library.js:52:28)
    at Win32ffi2.user32 (D:\ClassTools\dist\main\setAsWallpaper.js:2297:21)
    at Win32ffi2.winFns (D:\ClassTools\dist\main\setAsWallpaper.js:2304:37)
```

![winver](https://user-images.githubusercontent.com/18461360/168205925-4d9d7a55-fc3c-4005-b1f5-1250945ffa20.png)

**Comment by han9088** [comment]
@Clansty 提供下代码

**Comment by clansty** [comment]
> @Clansty 提供下代码

https://github.com/classtoolsofficial/classtools

在 Windows 7 下运行 `yarn dev` 即可复现

**Comment by han9088** [comment]
@Clansty 我试了下win11 是没有问题的，但手上没有win7的设备，我装个虚拟机再试试。

**Comment by clansty** [comment]
Windows 10.0.15063 也有发生这个问题

**Comment by han9088** [comment]
> Windows 10.0.15063 也有发生这个问题

这些都很老了，你照着这个再试试，可能是ffi的问题。

https://github.com/Nawbc/windows-shadow-legacy/blob/2e3504b60c1d61abcfd3c2093c2f63edd97c66ed/packages/shadow-addon/lib/shadow_window_action.ts#L105-L151

**Comment by han9088** [comment]
@Clansty 你再试下 alpha5 没有在win7上试，但应该没问题。

**Comment by clansty** [comment]
好诶，看起来可以了

@Nawbc

**Comment by han9088** [comment]
@Clansty 没问题 issue 我关了，有问题你再重新打开
